# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slates', '0002_auto_20161126_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='answer',
            field=models.CharField(default='option2', max_length=10),
        ),
        migrations.AddField(
            model_name='mcq',
            name='correct_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mcq',
            name='wrong_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mcqsets',
            name='set_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
